[gcp_service_account]
type = "service_account"
project_id = "cedar-context-452120-r1"
private_key_id = "4873773d14f08cf8a0596bc94a6891117cdd08e6"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDERI2euVEVn+it
Y5oRq9HW6z2CkpNWeSk06XnJULWDBYb8DRPoJfzGZ5EIpvKKWzNiF77EXhggETQ9
YMfl+k4nvUMu21kWF+E43iuXF9LPNur3THyCEIR1Y/kaBxfHkrsKD8f75EHyrLSK
s7VeC7fBYBADS2H/Y9+6WOP+sF3ZLwvONcQVudiwBKDkn3XpSww041YH9vDXMV5C
Oq/C8DgmkLB/x/aN9oCrfSin/3TvouDUwQMrH0VQjZXwrWbvC8ZBLFKDe7novhgq
kkcR9UOVOyRQ2ltudgcoQUbx3zdbnvPUP7CqH9sstdmjqRMgneffPebfHyXluzci
oHcmFUqrAgMBAAECggEAKkJUd+uQ8OYIdGTwxINJYEwwZ0/mF4VpAPKQfW86Vea3
xMeQFLkxLwsXqFRB/tZaPvG76o4UBbuOkvSmtfbqIxZWQ92I1f/4R4VWv2aqxmEd
wHegi2TBEIGhHiCO1zLZwPXa6nqgVH8pNIAzOfet7h4f9IWjqRi5EGeZV7pjyqI9
Ei/LMBkrcLzm+6hBY6Iw0cGcLl/wu0OJHbQNWutiY8otrX+hkwT8W0MoXbKiUeBM
h53OBI1uFiOwl///Txdkv7xuidxoAByoj9JNvIayLwHu+Vd54ZR4QSdk7XjInm71
Jz74kAIyCFi5MhlwwMCixvMKUdeHA8Or77FqXzEl6QKBgQDhCs+/HM3JueUG6832
NsYhEed1SyeBTfgZZKQqjSXP10OKZkBgVdkkJHOj5beyN4H8MnrSAudVCMGcoh4R
esC7gE1UzaURePwTgHgYZ9HsrFQijHee0PfDNeDvw33xoqSoWDaPVgu7tHyUFFZz
4L6xhTpb4fLUPkuIAyZMtBh6XwKBgQDfRGhoSG5z1PjWWylADsKXuKWGEJGya+Ip
uJNTicYsvzCs/YycW4R5GLBgS95Ij41R2XlN586F0Eg7fnrh3usXr6tWDlFDZSIH
69nSq5TgaZSf/t3vKE74+SZNn3IEAj4Gpoox6RUMI4FuJX1ZTx9HoVU2d9VG31rv
aUD7P0orNQKBgFRuRfshx2ODxxWNqrxRWIxXt0seYzf0FL0SMTV1t1X/IWvvaP+7
tbgFpQ08xmqqwK3qEoJwbHJO0rT9beKI935haKIEdYXUql52uJgPe4ccMIS1xrtj
E1G+CSJrafkaWESAtBea5NQLpyG3b6gSDfl0TqziXMSciqIA7IGin/xpAoGAbLLe
bh8Nf2FpwNrjK2fEP5/LHolElexGUO+m8p36GOEAbsiGw70esuJdRJTLZOJW+El7
8HzyJF3yPNzoML2aEY8aSKxxzfEX72lZRGL6+YMNtBOes4gZYsfSaSo+lUsOLai5
UXFcKOvEYP7plyiZXwNh/EG9WWL23+aLl4cJsh0CgYEAvikH6WBd4Z7Wd2hbjBsx
s/7yl3x8AypsuuFuVrZp7BSDfdXJVOnCWNB2/5fVNvFe89yAobG8EFStqPMWHWN9
HABs14yD5pZ5z+VWXc5TVC/0YCmJWXjtQaTIRPN4AotFmD0xHA/m8CJyOju8nHD7
vwnkLR2vGB/cfan+r3CmR3E=
-----END PRIVATE KEY-----"""
client_email = "sheets-access@cedar-context-452120-r1.iam.gserviceaccount.com"
client_id = "101025987916211430336"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/sheets-access%40cedar-context-452120-r1.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
